name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS-15 (arm64) – Go 1.16+
          - { image: macos-15, go: '1.18' }
          - { image: macos-15, go: '1.17' }
          - { image: macos-15, go: '1.16' }

          # macOS-14 (arm64) – Go 1.19+
          - { image: macos-14, go: '1.22' }
          - { image: macos-14, go: '1.21' }
          - { image: macos-14, go: '1.20' }
          - { image: macos-14, go: '1.19' }

          # Ubuntu 22.04 – GTK-3 / WebKit-4.1
          - { image: ubuntu-24.04, go: '1.22', apt: libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config }
          - { image: ubuntu-24.04, go: '1.21', apt: libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config }
          - { image: ubuntu-24.04, go: '1.20', apt: libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config }
          - { image: ubuntu-24.04, go: '1.19', apt: libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config }
          - { image: ubuntu-24.04, go: '1.18', apt: libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config }
          - { image: ubuntu-24.04, go: '1.17', apt: libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config }
          - { image: ubuntu-24.04, go: '1.16', apt: libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config }
          - { image: ubuntu-24.04, go: '1.15', apt: libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config }
          - { image: ubuntu-24.04, go: '1.14', apt: libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config }
          - { image: ubuntu-24.04, go: '1.13', apt: libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config }

          # Windows
          - { image: windows-latest, go: '1.22' }
          - { image: windows-latest, go: '1.21' }
          - { image: windows-latest, go: '1.20' }

    name: Build (${{ matrix.image }}, go ${{ matrix.go }})
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Linux dependencies
        if: runner.os == 'Linux' && matrix.apt
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ${{ matrix.apt }}
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Enable CGO
        run: echo "CGO_ENABLED=1" >> $GITHUB_ENV

      - name: Replace webview-go fork
        run: |
          echo "replace github.com/webview/webview_go => github.com/tester305/webview_go latest" >> go.mod
          go mod tidy
          go mod vendor

      - name: Build examples
        shell: bash
        run: |
          if [ "${{ matrix.dwarf_fix }}" = "true" ]; then
            go build -ldflags=-w ./examples/basic
            go build -ldflags=-w ./examples/bind
          else
            go build ./examples/basic
            go build ./examples/bind
          fi

      - name: Run tests
        run: go test -v ./...
