name: Continuous Build

on:
  push:
    branches: [master]       # your default branch
  workflow_dispatch:         # allows manual runs

permissions:
  contents: write            # needed for release creation

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
      fail-fast: false

    runs-on: ${{ matrix.goos == 'windows' && 'windows-latest' || matrix.goos == 'darwin' && 'macos-latest' || 'ubuntu-latest' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies (Linux/macOS)
        run: |
          if [[ "${{ matrix.goos }}" == "linux" ]]; then
            sudo apt update
            sudo apt install -y pkg-config libgtk-3-dev libwebkit2gtk-4.1-dev
          fi
          if [[ "${{ matrix.goos }}" == "darwin" ]]; then
            brew update
            brew install gtk+3 webkit2gtk
          fi
        shell: bash

      - name: Build binary
        run: |
          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            $env:GOOS="${{ matrix.goos }}"
            $env:GOARCH="${{ matrix.goarch }}"
            go build -v -o webview_go-windows-${{ matrix.goarch }}.exe
          else
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o webview_go-${{ matrix.goos }}-${{ matrix.goarch }}
          fi
        shell: bash

      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: webview_go-windows-${{ matrix.goarch }}
          path: webview_go-windows-${{ matrix.goarch }}.exe

      - name: Upload artifact (Linux/macOS)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: webview_go-${{ matrix.goos }}-${{ matrix.goarch }}
          path: webview_go-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Create or Update Continuous Build Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: continuous
          name: "Continuous Build"
          body: "Latest cross-platform build of webview_go (auto-updated on push)."
          files: ./dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
