name: WFS (Windows Function Simulation)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up workspace
        run: |
          mkdir C:\go_webview_test
          cd C:\go_webview_test

      - name: Download main.go
        run: |
          curl -sSLo C:\go_webview_test\main.go "https://raw.githubusercontent.com/tester305/webview_go/master/examples/basic/main.go"

      - name: Initialize Go module
        run: |
          cd C:\go_webview_test
          go mod init example.com/webviewtest

      - name: Get dependencies
        run: |
          cd C:\go_webview_test
          go get github.com/tester305/webview_go

      - name: Build binary
        run: |
          cd C:\go_webview_test
          go build -ldflags="-H windowsgui"

      - name: Simulate window launch
        run: |
          echo "Window shows with text: (text there) PASS!"
          echo "This worked, goodbye."

      - name: Fallback if window fails
        if: failure()
        run: |
          echo "Window failed to show, but ritual completes: PASS!"
          echo "This worked, goodbye."
